---

- hosts: web-servers
sudo: yes

task:

- name: update 

apt: update_cache=yes

- name: install apache2

apt: name=apache2 state=present

- name: restart apache2

service: name=apache2 state=restarted

- debug: msg="apache2 has been installed successfully"

